name: flutter_image_crop_plugin
description: A Flutter image crop plugin on iOS.
version: 1.1.3
author: Ning<lining201702@gmail.com>
homepage: https://github.com/NingLi-iOSer/flutter_image_crop_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutter_image_crop_plugin
    pluginClass: FlutterImageCropPlugin